require: rubocop-rspec

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - "config/**/*"

Style/Documentation:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: True

RSpec/NestedGroups:
  Max: 5

RSpec/LetSetup:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

# This seems very much personal choice, and would alter every string
# if we switched to the GDS standard.
Style/StringLiterals:
  EnforcedStyle: single_quotes

# I think we disagree with GDS on this one
Style/MethodCalledOnDoEndBlock:
  Enabled: false
