products:
  Moloko with Vellocet: 
    price: 10
    quantity: 2
  Moloko with Synthemesc: 
    price: 12.25
    quantity: 4
  Moloko with Drencrom: 
    price: 15.85
    quantity: 1
  Orange with knives: 
    price: 5
    quantity: 6
  Ultraviolence booster:
    price: 2.50
    quantity: 10

change:
  £2: 6
  £1: 10
  0.50p: 25
  0.20p: 30
  0.10p: 50
  0.05p: 60
  0.02p: 70
  0.01p: 80
